spring:
  application:
    name: user_center-backend
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: zhang2004
    url: jdbc:mysql://localhost:3306/user_center
  session:
    timeout: 86400                                # session 设置失效时间为一天（86400 秒）
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER


server:
  port: 8090
  servlet:
    context-path: /api


mybatis-plus:
  configuration:
    map-underscore-to-camel-case: false           # 关闭数据库中的的字段自动将下划线转成驼峰
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl   # 开启日志查询
  global-config:
    db-config:
      logic-delete-field: isDelete                # 定义全局逻辑删除的字段名
      logic-delete-value: 1                    # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0                 # 逻辑未删除值(默认为 0)